import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BookOpen, Plus, BarChart3 } from 'lucide-react';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import { ThemeToggle } from './ThemeToggle';
export function Header(_a) {
    var onAddTransaction = _a.onAddTransaction, onToggleBalances = _a.onToggleBalances;
    var isMobile = useMediaQuery('(max-width: 768px)');
    return (_jsx("header", { className: "sticky top-0 z-50 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 w-full", children: _jsx("div", { className: "w-full px-4 py-3", children: _jsxs("div", { className: "flex items-center justify-between w-full", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0 flex-1", children: [_jsx("div", { className: "p-1.5 bg-primary/10 rounded-md flex-shrink-0", children: _jsx(BookOpen, { className: "h-5 w-5 text-primary" }) }), _jsxs("div", { className: "min-w-0", children: [_jsx("h1", { className: "text-lg font-bold truncate", children: "Ledger UI" }), _jsx("p", { className: "text-xs text-muted-foreground hidden xs:block", children: "Double-entry bookkeeping" })] })] }), _jsxs("div", { className: "flex items-center gap-2 flex-shrink-0", children: [isMobile && (_jsx("button", { onClick: onToggleBalances, className: "h-9 w-9 p-0 rounded-md border border-input bg-background hover:bg-accent hover:text-accent-foreground", children: _jsx(BarChart3, { className: "h-4 w-4" }) })), _jsxs("button", { onClick: onAddTransaction, className: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2", children: [_jsx(Plus, { className: "mr-2 h-4 w-4" }), "New Transaction"] }), _jsx(ThemeToggle, {})] })] }) }) }));
}
